### ISSUE TITLE
Tendermint proposal problem

### ISSUE THREAD

**Issue by dakk** [openbitlab/srvcheck#137]
![image](https://github.com/openbitlab/srvcheck/assets/1060425/ebfc4fac-8caa-4835-92f5-f13df8d7d9c7)

**Comment by Lu191** [comment]
This is a problem only on quicksilver, and seems like a misconfiguration on their side.
![immagine](https://github.com/openbitlab/srvcheck/assets/49374667/fd47505b-46f5-495f-b2f8-c036835c892a)

Close #137
