### ISSUE TITLE
Task APT throws error in a fresh installation

### ISSUE THREAD

**Issue by Lu191** [openbitlab/srvcheck#157]
![immagine](https://github.com/openbitlab/srvcheck/assets/49374667/efc6b19b-a9fb-456f-a773-63da887f5ff4)

This seems to fix the issue:
`apt-get install --reinstall python3-apt`

**Comment by dakk** [comment]
Python3-apt should be present in any apt based installation; could you please post the linux version?
Anyway, it needs to be handled
